"""initial schema

Revision ID: d7e8453e9723
Revises: 
Create Date: 2026-08-02 09:54:24.252980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e8453e9723'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('floor', sa.String(), nullable=False),
    sa.Column('polygon', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('amperage', sa.Integer(), nullable=True),
    sa.Column('fed_from_panel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fed_from_panel_id'], ['panels.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('circuits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('breaker_label', sa.String(), nullable=False),
    sa.Column('amperage', sa.Integer(), nullable=True),
    sa.Column('poles', sa.Integer(), server_default='1', nullable=False),
    sa.Column('panel_sticker_text', sa.String(), nullable=True),
    sa.Column('verified_description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('circuit_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('circuit_points')
    op.drop_table('circuits')
    op.drop_table('panels')
    op.drop_table('rooms')
    # ### end Alembic commands ###
